apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-blue
#  namespace: nginx-blue
spec:
  selector:
    matchLabels:
      app: nginx-color
  template:
    metadata:
      labels:
        app: nginx-color
    spec:
      containers:
      - name: container-nginx-color
        image: docker.io/rof1966/nginx-color:blue
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        
